"""empty message

Revision ID: 3e0046b1e483
Revises: 
Create Date: 2020-11-24 14:23:20.778692

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '3e0046b1e483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alternate_id', sa.String(length=256), nullable=False),
    sa.Column('social_id', sa.String(length=256), nullable=True),
    sa.Column('nickname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('picture', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('family_name', sa.String(length=256), nullable=True),
    sa.Column('given_name', sa.String(length=256), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sqlalchemy_utils.types.arrow.ArrowType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alternate_id'),
    sa.UniqueConstraint('social_id')
    )
    op.create_index(op.f('ix_userprofile_created_at'), 'userprofile', ['created_at'], unique=False)
    op.create_index(op.f('ix_userprofile_updated_at'), 'userprofile', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprofile_updated_at'), table_name='userprofile')
    op.drop_index(op.f('ix_userprofile_created_at'), table_name='userprofile')
    op.drop_table('userprofile')
    # ### end Alembic commands ###
